### ISSUE TITLE
Error required when serializer is not specified

### ISSUE THREAD

**Issue by IvanGrgurevic** [infinum/json_api_responders#2]
With the new update we are required to specify the exact serializer, and when working with old code, this can be a pain to debug. When the serializer is not specified, the issue shows up later in the code, and there is no indication that the issue arises from the #respond_with method.

**Comment by d4be4st** [comment]
this might be a bit out of the scope for the gem. No one is saying you need to use AMS for this.

**Comment by IvanGrgurevic** [comment]
maybe have a config where you can specify required options?

**Comment by d4be4st** [comment]
Feel free to create a PR :)

**Comment by d4be4st** [comment]
fix #3
